"""
Debug reader for chunks.pkl files generated by index_repo.py.

This script loads and displays the contents of a chunks.pkl file in a readable format,
organizing chunks by type (code chunks, file summaries, folder summaries) with relevant metadata.
"""

import pickle
from typing import Dict, List, Any
from collections import defaultdict


def load_chunks(chunks_file_path: str) -> List[Dict[str, Any]]:
    """
    Load chunks from a pickle file.

    Args:
        chunks_file_path: Path to the chunks.pkl file

    Returns:
        List of chunk dictionaries containing 'text' and 'metadata' keys
    """
    try:
        with open(chunks_file_path, "rb") as file_handle:
            chunks = pickle.load(file_handle)
        return chunks
    except FileNotFoundError:
        print(f"Error: File '{chunks_file_path}' not found.")
        return []
    except Exception as error:
        print(f"Error loading chunks: {error}")
        return []


def categorize_chunks(chunks: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """
    Categorize chunks by their level type.

    Args:
        chunks: List of chunk dictionaries

    Returns:
        Dictionary grouping chunks by level (code_chunk, file_summary, folder_summary)
    """
    categorized = defaultdict(list)
    for chunk in chunks:
        level = chunk.get("metadata", {}).get("level", "unknown")
        categorized[level].append(chunk)
    return categorized


def display_code_chunk(chunk: Dict[str, Any], index: int) -> None:
    """
    Display a code chunk with its metadata.

    Args:
        chunk: Chunk dictionary containing text and metadata
        index: Index number for display
    """
    metadata = chunk.get("metadata", {})
    file_path = metadata.get("file", "unknown")
    start_line = metadata.get("start_line", "?")
    end_line = metadata.get("end_line", "?")
    chunk_type = metadata.get("type", "unknown")

    print(f"\n--- Code Chunk #{index} ---")
    print(f"File: {file_path}")
    print(f"Type: {chunk_type}")
    print(f"Lines: {start_line}-{end_line}")
    print("Content:")
    print("-" * 50)
    print(chunk.get("text", ""))
    print("-" * 50)


def display_file_summary(chunk: Dict[str, Any], index: int) -> None:
    """
    Display a file summary chunk with its metadata.

    Args:
        chunk: Chunk dictionary containing text and metadata
        index: Index number for display
    """
    metadata = chunk.get("metadata", {})
    file_path = metadata.get("file", "unknown")

    print(f"\n--- File Summary #{index} ---")
    print(f"File: {file_path}")
    print("Summary:")
    print("-" * 50)
    print(chunk.get("text", ""))
    print("-" * 50)


def display_folder_summary(chunk: Dict[str, Any], index: int) -> None:
    """
    Display a folder summary chunk with its metadata.

    Args:
        chunk: Chunk dictionary containing text and metadata
        index: Index number for display
    """
    metadata = chunk.get("metadata", {})
    folder_path = metadata.get("folder", "unknown")

    print(f"\n--- Folder Summary #{index} ---")
    print(f"Folder: {folder_path}")
    print("Summary:")
    print("-" * 50)
    print(chunk.get("text", ""))
    print("-" * 50)


def display_chunks(chunks_file_path: str) -> None:
    """
    Load and display chunks from a pickle file in a organized manner.

    Args:
        chunks_file_path: Path to the chunks.pkl file
    """
    chunks = load_chunks(chunks_file_path)

    if not chunks:
        print("No chunks to display.")
        return

    print(f"Loaded {len(chunks)} chunks from {chunks_file_path}")
    print("=" * 80)

    categorized = categorize_chunks(chunks)

    # Display code chunks
    if "code_chunk" in categorized:
        print(f"\n📄 CODE CHUNKS ({len(categorized['code_chunk'])} total)")
        print("=" * 80)
        for index, chunk in enumerate(categorized["code_chunk"], 1):
            display_code_chunk(chunk, index)

    # Display file summaries
    if "file_summary" in categorized:
        print(f"\n📁 FILE SUMMARIES ({len(categorized['file_summary'])} total)")
        print("=" * 80)
        for index, chunk in enumerate(categorized["file_summary"], 1):
            display_file_summary(chunk, index)

    # Display folder summaries
    if "folder_summary" in categorized:
        print(f"\n📂 FOLDER SUMMARIES ({len(categorized['folder_summary'])} total)")
        print("=" * 80)
        for index, chunk in enumerate(categorized["folder_summary"], 1):
            display_folder_summary(chunk, index)

    # Display unknown chunks if any
    if "unknown" in categorized:
        print(f"\n❓ UNKNOWN CHUNKS ({len(categorized['unknown'])} total)")
        print("=" * 80)
        for index, chunk in enumerate(categorized["unknown"], 1):
            print(f"\n--- Unknown Chunk #{index} ---")
            print(f"Metadata: {chunk.get('metadata', {})}")
            print("Content:")
            print("-" * 50)
            print(chunk.get("text", ""))
            print("-" * 50)


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("Usage: python debug_reader.py <chunks.pkl file path>")
        print("Example: python debug_reader.py test/chunks.pkl")
        sys.exit(1)

    chunks_file = sys.argv[1]
    display_chunks(chunks_file)
